### ISSUE TITLE
Error: Cannot find module 'C:\Users\hyung\Desktop\whatsapp\node_modules\baileys\lib\index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by hyung27** [zaadevofc/zaileys#1]
Error: Cannot find module 'C:\Users\hyung\Desktop\whatsapp\node_modules\baileys\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\hyung\Desktop\whatsapp\node_modules\zaiyes\dist\index.js:1:1033)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\hyung\\Desktop\\whatsapp\\node_modules\\baileys\\package.json',
  requestPath: 'baileys'
}

**Comment by hyung27** [comment]
Kode saya

`import { Client } from "zaiyes";

const connOptions = {
    authors: [""],
    ignoreMe: false,
    markOnline: true,
    pairing: true,
    phoneNumber: "",
    showLogs: true,
}

async function connect() {
    const sock = new Client(connOptions);

    sock.on("message", ctx => {
        console.log(ctx);
    });

    sock.on("connection", ctx => {
        console.log(ctx);
    });

    return sock;
}

connect();`

**Comment by hyung27** [comment]
kode saya

```
import { Client } from "zaiyes";

const connOptions = {
    authors: [""],
    ignoreMe: false,
    markOnline: true,
    pairing: true,
    phoneNumber: "",
    showLogs: true,
}

async function connect() {
    const sock = new Client(connOptions);

    sock.on("message", ctx => {
        console.log(ctx);
    });

    sock.on("connection", ctx => {
        console.log(ctx);
    });

    return sock;
}

connect();
```

**Comment by zaadevofc** [comment]
> kode saya
> 
> ```
> import { Client } from "zaiyes";
> 
> const connOptions = {
>     authors: [""],
>     ignoreMe: false,
>     markOnline: true,
>     pairing: true,
>     phoneNumber: "",
>     showLogs: true,
> }
> 
> async function connect() {
>     const sock = new Client(connOptions);
> 
>     sock.on("message", ctx => {
>         console.log(ctx);
>     });
> 
>     sock.on("connection", ctx => {
>         console.log(ctx);
>     });
> 
>     return sock;
> }
> 
> connect();
> ```
> 

Package kamu salah bro, bukan zaileys tapi zaileys

`import { Client } from 'zaileys'`

Npm : https://npmjs.com/package/zaileys

**Comment by zaadevofc** [comment]
> kode saya
> 
> ```
> import { Client } from "zaiyes";
> 
> const connOptions = {
>     authors: [""],
>     ignoreMe: false,
>     markOnline: true,
>     pairing: true,
>     phoneNumber: "",
>     showLogs: true,
> }
> 
> async function connect() {
>     const sock = new Client(connOptions);
> 
>     sock.on("message", ctx => {
>         console.log(ctx);
>     });
> 
>     sock.on("connection", ctx => {
>         console.log(ctx);
>     });
> 
>     return sock;
> }
> 
> connect();
> ```

penulisan kode nya tidak tepat. untuk referensi silahkan buka file testing disini : https://github.com/zaadevofc/zaileys/blob/main/src/test/index.ts
